@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

SqlSession <|-- SqlSessionFactory

class ArrayList {
Object[] elementData
size()
}

interface SqlSession {
Configuration getConfiguration();
<T> T getMapper(Class<T> type);
Connection getConnection();
void commit(boolean force);
void rollback();
void select(String statement, Object parameter, ResultHandler handler);
int insert(String statement, Object parameter);

}

interface SqlSessionFactory {
SqlSession openSession(Connection connection);
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml